<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto

namespace App\V2ray\Core\App\Stats\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.v2ray.core.app.stats.command.SysStatsResponse</code>
 */
class SysStatsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 NumGoroutine = 1;</code>
     */
    protected $NumGoroutine = 0;
    /**
     * Generated from protobuf field <code>uint32 NumGC = 2;</code>
     */
    protected $NumGC = 0;
    /**
     * Generated from protobuf field <code>uint64 Alloc = 3;</code>
     */
    protected $Alloc = 0;
    /**
     * Generated from protobuf field <code>uint64 TotalAlloc = 4;</code>
     */
    protected $TotalAlloc = 0;
    /**
     * Generated from protobuf field <code>uint64 Sys = 5;</code>
     */
    protected $Sys = 0;
    /**
     * Generated from protobuf field <code>uint64 Mallocs = 6;</code>
     */
    protected $Mallocs = 0;
    /**
     * Generated from protobuf field <code>uint64 Frees = 7;</code>
     */
    protected $Frees = 0;
    /**
     * Generated from protobuf field <code>uint64 LiveObjects = 8;</code>
     */
    protected $LiveObjects = 0;
    /**
     * Generated from protobuf field <code>uint64 PauseTotalNs = 9;</code>
     */
    protected $PauseTotalNs = 0;
    /**
     * Generated from protobuf field <code>uint32 Uptime = 10;</code>
     */
    protected $Uptime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $NumGoroutine
     *     @type int $NumGC
     *     @type int|string $Alloc
     *     @type int|string $TotalAlloc
     *     @type int|string $Sys
     *     @type int|string $Mallocs
     *     @type int|string $Frees
     *     @type int|string $LiveObjects
     *     @type int|string $PauseTotalNs
     *     @type int $Uptime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 NumGoroutine = 1;</code>
     * @return int
     */
    public function getNumGoroutine()
    {
        return $this->NumGoroutine;
    }

    /**
     * Generated from protobuf field <code>uint32 NumGoroutine = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNumGoroutine($var)
    {
        GPBUtil::checkUint32($var);
        $this->NumGoroutine = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 NumGC = 2;</code>
     * @return int
     */
    public function getNumGC()
    {
        return $this->NumGC;
    }

    /**
     * Generated from protobuf field <code>uint32 NumGC = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNumGC($var)
    {
        GPBUtil::checkUint32($var);
        $this->NumGC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Alloc = 3;</code>
     * @return int|string
     */
    public function getAlloc()
    {
        return $this->Alloc;
    }

    /**
     * Generated from protobuf field <code>uint64 Alloc = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAlloc($var)
    {
        GPBUtil::checkUint64($var);
        $this->Alloc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 TotalAlloc = 4;</code>
     * @return int|string
     */
    public function getTotalAlloc()
    {
        return $this->TotalAlloc;
    }

    /**
     * Generated from protobuf field <code>uint64 TotalAlloc = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalAlloc($var)
    {
        GPBUtil::checkUint64($var);
        $this->TotalAlloc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Sys = 5;</code>
     * @return int|string
     */
    public function getSys()
    {
        return $this->Sys;
    }

    /**
     * Generated from protobuf field <code>uint64 Sys = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSys($var)
    {
        GPBUtil::checkUint64($var);
        $this->Sys = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Mallocs = 6;</code>
     * @return int|string
     */
    public function getMallocs()
    {
        return $this->Mallocs;
    }

    /**
     * Generated from protobuf field <code>uint64 Mallocs = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMallocs($var)
    {
        GPBUtil::checkUint64($var);
        $this->Mallocs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Frees = 7;</code>
     * @return int|string
     */
    public function getFrees()
    {
        return $this->Frees;
    }

    /**
     * Generated from protobuf field <code>uint64 Frees = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFrees($var)
    {
        GPBUtil::checkUint64($var);
        $this->Frees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 LiveObjects = 8;</code>
     * @return int|string
     */
    public function getLiveObjects()
    {
        return $this->LiveObjects;
    }

    /**
     * Generated from protobuf field <code>uint64 LiveObjects = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLiveObjects($var)
    {
        GPBUtil::checkUint64($var);
        $this->LiveObjects = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 PauseTotalNs = 9;</code>
     * @return int|string
     */
    public function getPauseTotalNs()
    {
        return $this->PauseTotalNs;
    }

    /**
     * Generated from protobuf field <code>uint64 PauseTotalNs = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPauseTotalNs($var)
    {
        GPBUtil::checkUint64($var);
        $this->PauseTotalNs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 Uptime = 10;</code>
     * @return int
     */
    public function getUptime()
    {
        return $this->Uptime;
    }

    /**
     * Generated from protobuf field <code>uint32 Uptime = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkUint32($var);
        $this->Uptime = $var;

        return $this;
    }

}

