<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

namespace GPBMetadata;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7a0a0c636f6e6669672e70726f746f12186170702e76327261792e636f" .
            "72652e6170702e737461747322080a06436f6e666967423e0a18636f6d2e" .
            "76327261792e636f72652e6170702e737461747350015a057374617473aa" .
            "02184170702e56325261792e436f72652e4170702e537461747362067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

